title: "Seth Johnston"
email: seth@sethmichaeljohnston.com
description:  >- # this means to ignore newlines until "baseurl:"
baseurl: "SethMJohnston/SethMJohnston.github.io" 
url: "/portfolio-template" 
twitter_username: nikeseth01
github_username:  SethMJohnston

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg

theme: jekyll-theme-cayman
