title: "Seth Johnston"
email: seth@sethmichaeljohnston.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "SethMJohnston/SethMJohnston.github.io" 
url: "/portfolio-template" 
twitter_username: nikeseth01
github_username:  SethMJohnston

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg

theme: jekyll-theme-cayman
